version: "3.7"
services:
  smartvoucher-mysql-db:
    container_name: smartvoucher-mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Adc12345
      MYSQL_DATABASE: CybersoftProject
    ports:
      - "3307:3306"
    volumes:
      - ./database/ProjectDBCybersoftBC02.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - smartvoucher-network

  smartvoucher-redis:
    image: redis:latest
    container_name: smartvoucher-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - smartvoucher-network

  smartvoucher-service:
    container_name: smartvoucher-service
    build:
      context: .
      dockerfile: DockerFileSpringboot
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://smartvoucher-mysql-db:3307/CybersoftProject
      MYSQL_ROOT_PASSWORD: Adc12345
      REDIS_HOST: smartvoucher-redis
    depends_on:
      - smartvoucher-mysql-db
    networks:
      - smartvoucher-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  voucher-frontend-container:
    container_name: voucher-frontend-container
    build:
      context: .
      dockerfile: DockerFileVoucherFE
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - smartvoucher-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  smartvoucher-network:
      name: smartvoucher-network
      driver: bridge

#docker-compose -f ./docker-compose.yml up -d mysql8-container
#docker-compose -f ./docker-compose.yml up -d redis-container
#docker-compose -f ./docker-compose.yml up -d smartvoucher-container --build
#docker-compose -f ./docker-compose.yml up -d voucher-frontend-container --build


